FROM eclipse-temurin:17-jdk-alpine
COPY /build/install/neural-meduza-discord-broadcaster /neural-meduza-discord-broadcaster
ENTRYPOINT /neural-meduza-discord-broadcaster/bin/neural-meduza-discord-broadcaster