version: '3.8'

volumes:
  pdb-redis-data:
    driver: local

networks:
  pdb-net:
    driver: bridge

services:
  panorama-discord-broadcaster:
    image: panorama-discord-broadcaster:latest
    container_name: panorama-discord-broadcaster
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    networks:
      - pdb-net
    restart: always

  panorama-discord-broadcaster-redis:
    image: redis:latest
    container_name: panorama-discord-broadcaster-redis
    expose:
      - 6379
    volumes:
      - pdb-redis-data:/data
    networks:
      - pdb-net
    restart: always